### ISSUE TITLE
Balance Sheet

### ISSUE THREAD

**Issue by hidayat-ullah** [prashants/webzash-v1-defunct#24]
I want to view Report By Date ( I Want to ad search by date system on report view page )
its just for Balance sheet OR for All Don't Matter 
 so please tel me How i can manage this on balancesheet.php page or another pages

**Comment by prashants** [comment]
I hope you are using the new version of Webzash.

Beta version is available at

Download the TAR.GZ version below :
https://dl.dropboxusercontent.com/u/50842471/webzash-beta.tar.gz

Download the ZIP version below :
https://dl.dropboxusercontent.com/u/50842471/webzash-beta.zip

**Comment by hidayat-ullah** [comment]
thanks bro

**Comment by hidayat-ullah** [comment]
Cound not connect to database. Please, check your database settings.

Mean..?

**Comment by prashants** [comment]
Are you using the new version of webzash with older database ?

**Comment by hidayat-ullah** [comment]
I have Created a new database

**Comment by prashants** [comment]
So you are facing this issue when activating the account ?

**Comment by hidayat-ullah** [comment]
yes

**Comment by prashants** [comment]
I hope you have extracted the setup in a clean folder because someone recently faced some database issue which was solved by extracting it in fresh folder and recreated the account from scratch.

**Comment by hidayat-ullah** [comment]
okay I am going to do so. If I didn't get it solved I will contact you again. Thanks

**Comment by prashants** [comment]
ok

**Comment by hidayat-ullah** [comment]
I am still getting the same error. It is saying to check the database settings. Could you please help to get this problem fixed or if there is any option or any code required to be added in the last version of webzash to show the reports whatever the date we put, as I am using that version of your to manage my accounts

**Comment by prashants** [comment]
Ya I will help you fix the issue. Can you check your database whether tables have been created ?

**Comment by hidayat-ullah** [comment]
yes I am using it for months

**Comment by prashants** [comment]
Can you send me a screenshot of the error.

**Comment by prashants** [comment]
Upload it to http://imgur.com

**Comment by prashants** [comment]
Link ?

**Comment by hidayat-ullah** [comment]
http://imgur.com/Ewhpbrm

**Comment by prashants** [comment]
So you are facing issue when creating an account - I thought you were facing issue when activating an acount.

What are the database setting that you are using ?

**Comment by hidayat-ullah** [comment]
i am using Xampp  
host is localhost
user is root
password is null

**Comment by prashants** [comment]
port ?

**Comment by hidayat-ullah** [comment]
8080

**Comment by prashants** [comment]
Database port should be 3306. Please try that.

**Comment by hidayat-ullah** [comment]
ok thanks

**Comment by prashants** [comment]
8080 will be the web server port.

**Comment by prashants** [comment]
So did it work ?

**Comment by hidayat-ullah** [comment]
Unfortunately no.
Can you please connect  with me through Teamviewer ?

**Comment by hidayat-ullah** [comment]
ok

**Comment by hidayat-ullah** [comment]
kindly 
Check your mail box

**Comment by hidayat-ullah** [comment]
Thank you so much.

**Comment by prashants** [comment]
I got disconnected. Did it activate ?

I will fix the password issue in the final release.

**Comment by hidayat-ullah** [comment]
Yes it is, but i didn't found view reports by date option in there

**Comment by prashants** [comment]
You can get ledger statement and reconciliation by date :) Maybe I will add it for Balance Sheet and Profit and Loss later.

**Comment by prashants** [comment]
I have fixed the password and email issue in the latest commit.

**Comment by hidayat-ullah** [comment]
If fetching reports by date is possible in last version which is created on codeigniter then plz Let me Know

**Comment by prashants** [comment]
None of the versions have that. I can implement it in the new version. Let me know exactly what you want.

**Comment by prashants** [comment]
Exactly what kind of reports you want in month wise format ?

I definitely what to see what changes you made.

I will not be supporting the CI version in future since there have been some licensing changes with CI which forced me to switch to cakephp.

**Comment by hidayat-ullah** [comment]
Ok i m gonna send you Details on mail

**Comment by hidayat-ullah** [comment]
prashants.mombail@gmail.com 
Is it Correct ..?

**Comment by prashants** [comment]
its pshah.mumbai at gmail.com

**Comment by hidayat-ullah** [comment]
ok

**Comment by prashants** [comment]
How did you implement cheque number and post dated ?

**Comment by hidayat-ullah** [comment]
In Post Dated option select Bank al habib
Its for Check Withdrawal dates

Which Deduct Balance from account While date is arrived and It show how many checks Is Issued 
and When Will Be deducted

**Comment by prashants** [comment]
You have done some really cool stuff man.

Its will be great if you can push your code upsteams. I want to integrate it with final version of webzash. You will get full credit for it.

**Comment by hidayat-ullah** [comment]
Yes I will provide it to you.
Could you please solve my problem?

**Comment by prashants** [comment]
Yes we can work together to solve your issues.

**Comment by prashants** [comment]
I will assign you certian things, will you do them ?

**Comment by hidayat-ullah** [comment]
Yes of course

**Comment by prashants** [comment]
Great. So first thing you need to do is create a detail plan on what things you want in the wiki below.

https://github.com/prashants/webzash/wiki/Swiftcoders-Integration

Let me know if you cant edit the page.

I will review the plan tomorrow and we will discuss how we can split the work.

**Comment by hidayat-ullah** [comment]
OK

**Comment by prashants** [comment]
CI has its own way or writing querries, you will have to use that. Check the user_guide folder under the old setup.

user_guide/database/queries.html

**Comment by hidayat-ullah** [comment]
I know But i m unable to find that where i have to write Or change query in webzash
Its my main problem
And I have Requested you to solve this issue only Because you Know which query belong to Reports
and what we have to change for this implement and I hope Its'nt an issue for you
m i right..?

**Comment by prashants** [comment]
You have to make changes in

https://github.com/prashants/webzash/blob/v1.x/system/application/controllers/report.php

https://github.com/prashants/webzash/tree/v1.x/system/application/views/report

I hope you know how to work with a MVC architecture.

**Comment by hidayat-ullah** [comment]
Bro.., as I said i m not familiar with MVC Concepts

**Comment by prashants** [comment]
Try to go through the user guide. It will help.

**Comment by hidayat-ullah** [comment]
In these pages you have loaded many methods / Classes  and models and I think some of these related  to reports 
so if I want to make changes I must have to learn CI from Scratch..,
Because I m reading  user guide since morning But (Kuch pally nahi parha)

**Comment by prashants** [comment]
I strongly suggest you go with the new version which is using cakephp.

Also it will take you sometime to learn a MVC based framework. It can't be learnt it a day. Try out the examples, etc.

**Comment by hidayat-ullah** [comment]
But the problem is still here.., we are  using CI version for a couple of weeks  which i have
Customized according to Boss's Requirements.., unfortunately we have to go with same CI version 
 tomorrow i will call you to join me on teamviewer  
I hope you will not Deny for technical Help

**Comment by prashants** [comment]
What are the customizations that you made ?

**Comment by prashants** [comment]
I already saw few of them. Is there anything more that you have added ?

**Comment by prashants** [comment]
I am working on added custom date to balance sheet and profit and loss in new version. Is there anything else you want in reports ? Custom date is already present in ledger statement and reconciliation.

As for the changes you made in older version I will help you carry them forward to new version.

**Comment by hidayat-ullah** [comment]
Are you going with same Database structure..?
Because I will Import our Former Data to new cakephp version..
And also I have Added 2 more fields in entries table (Check_num  AND  Post_Dated)

**Comment by prashants** [comment]
Yes it 90% same.

**Comment by hidayat-ullah** [comment]
90% mean will not be able to import our records..?

**Comment by prashants** [comment]
There are some very minor changes which will not affect you, I will provide a script to import from older version.

**Comment by prashants** [comment]
Will this do ?

http://imgur.com/ut7Y3mQ

**Comment by hidayat-ullah** [comment]
That's really awesome .. May i know when you will complete the final version..

**Comment by prashants** [comment]
Most of the work is done, some final touches are remaining. So you can start using it if you want to.

**Comment by prashants** [comment]
I couldnt see the entry part in the link that you sent yesterday. I want to see how you have done that.

Why dont you use reconciliation for that purpose ?

Also you can use cheque date and cheque number rather than post dated.

**Comment by hidayat-ullah** [comment]
Filed name Does'nt  matter its  withdrawal date ..,
But the 2 extra fields data shout be insert  in entries table

**Comment by prashants** [comment]
Ya show me know what all changes you have made.

**Comment by hidayat-ullah** [comment]
The link which I have sent .. Is a Separate Folder just belong to database only (Not with CI)..,  
In CI we have just Added  2 input Fields

**Comment by prashants** [comment]
ok

**Comment by prashants** [comment]
Ok.

**Comment by prashants** [comment]
I have updated profit and loss to support date range. Please check it and let me know if its ok. I will implement the same in balance sheet if its ok from your side.

How to update :
1. Copy the app/Plugin/Webzash/Database folder somewhere
2. Delete the app/Plugin/Webzash folder.
3. Download the latest code from https://bitbucket.org/prashants/webzash and extract it to app/Plugin/Webzash folder
4. Replace the file from step 1.

**Comment by hidayat-ullah** [comment]
ok

**Comment by hidayat-ullah** [comment]
Great.., I think it will work properly.., 
Now can I import Database Normally..?

**Comment by hidayat-ullah** [comment]
DB is too Different from last one

**Comment by prashants** [comment]
I will give you the script to update db by tom.

**Comment by hidayat-ullah** [comment]
Ok.., and what about two extra  fields for Entries which I requested..?

**Comment by prashants** [comment]
I have not decided on that. Once I complete the reports I will decide on it.

**Comment by prashants** [comment]
I have added custom date to balance sheet also.

**Comment by hidayat-ullah** [comment]
Ok., But Extra fields Should be Optional (Not Required)

**Comment by prashants** [comment]
ok

**Comment by prashants** [comment]
This week

**Comment by hidayat-ullah** [comment]
Let me know if you have done so..,

**Comment by prashants** [comment]
Sorry I am out of touch since last few days. I will get back to you next week.

**Comment by hidayat-ullah** [comment]
ok

**Comment by hidayat-ullah** [comment]
what about completion ..?

**Comment by prashants** [comment]
I will be available from monday onwards.

**Comment by hidayat-ullah** [comment]
are you there..?

**Comment by prashants** [comment]
Ya I am back.

**Comment by hidayat-ullah** [comment]
any update..?

**Comment by prashants** [comment]
I will have a beta release by next week.

**Comment by prashants** [comment]
Beta 2 version of Webzash-Next has been released.

Download the TAR.GZ version below :
https://www.dropbox.com/s/c6oe3z5vldu1j32/webzash-beta2.tar.gz?dl=0

Download the ZIP version below :
https://www.dropbox.com/s/bndxogrpal5wz9m/webzash-beta2.zip?dl=0

**Comment by prashants** [comment]
I have thought about the extra fields in the entries, doing that will require much more changes, like adding corresponding bill number / date, support for paying by multiple cheques within a single entry. I need to work out a common solution for this. For now, I suggest you make your own changes in the entry code. I can help if you get stuck anywhere.

**Comment by prashants** [comment]
I will be proving the update script soon for converting from older to new version of webzash. I will update you accordingly.

**Comment by hidayat-ullah** [comment]
ok and what about multiple print option for entries

**Comment by prashants** [comment]
There are some imp stuff that I need to complete first like update script, etc. I will do that later.

**Comment by hidayat-ullah** [comment]
ok .., I will try to add extra fields in entries But Let me Know specific pages so i can safe time

**Comment by prashants** [comment]
I will guide you once I complete the udpate script.

**Comment by hidayat-ullah** [comment]
ok.., thanks

**Comment by hidayat-ullah** [comment]
have you done..?

**Comment by prashants** [comment]
I have completed the update script.

https://bitbucket.org/prashants/webzash/raw/495600d2dffed67ff46a52f0716299816487fe49/Config/Migrate/Migrate.v4.to.v5.MySQL.sql

You have to run this script against the older database.

IMPORTANT !! Please run this script on a backup copy of database and let me know if it works.

I am planning to release final beta this weekend which will have everything.

Then after testing everything I am planning to release final version next weekend.

**Comment by hidayat-ullah** [comment]
ok let me check..!

**Comment by prashants** [comment]
Run this also after running the migration scipt...

UPDATE `settings` SET `database_version` = '5' WHERE `id` = 1;

The migration script will take some time to run. Do wait for a while.

**Comment by hidayat-ullah** [comment]
ya it works..
but now i have to delete testing data from new version to import old database and i am unable to
delete data from any table its showing foreign key Error

**Comment by prashants** [comment]
The script will automatically update the data also. Just copy the entire old database and run the script against it. It will handle the rest.

Do keep a backup. This is just for testing. I haven't yet tested it throughly.

**Comment by hidayat-ullah** [comment]
the data in new version is only for testing i dont wanna keep it 
i have to overwrite but its not working

**Comment by hidayat-ullah** [comment]
its showing the following error while overwriting 
SQL query:

-- -- Dumping data for table `entries` -- INSERT INTO `entries` (`id`, `tag_id`, `entrytype_id`, `number`, `date`, `dr_total`, `cr_total`, `narration`, `cheque_num`, `posted_date`) VALUES (3, NULL, 4, 1, '2014-08-20', '9000.00', '9000.00', 'For Kiddil On 09/08 to 14/08', '0', '0000-00-00'), (5, NULL, 4, 2, '2014-08-02', '231600.00', '231600.00', 'MUKHTAR FOR 2115 KGS IND MAK', '0', '0000-00-00'), (6, NULL, 4, 3, '2014-08-03', '345400.00', '345400.00', 'MUKHTAR FOR 3006 KGS IND MAK', '0', '0000-00-00'), (7, NULL, 4, 4, '2014-08-04', '352400.00', '352400.00', 'MUKHTAR FOR 2934 KGS IND MAK', '0', '0000-00-00'), (8, NULL, 4, 5, '2014-08-05', '551500.00', '551500.00', 'MUKHTAR FOR 4410 KGS IND MAK', '0', '0000-00-00'), (9, NULL, 4, 6, '2014-08-06', '146100.00', '146100.00', 'MUKHTAR FOR 1170 KGS IND MAK', '0', '0000-00-00'), (10, NULL, 4, 7, '2014-08-07', '16100.00', '16100.00', 'MUKHTAR FOR 530 KGS SARDIN FISH', '0', '0000-00-00'), (11, NULL, 4, 8, '2014-08-07', '378900.00', '378900.00'[...]

MySQL said: Documentation

#1062 - Duplicate entry '3' for key 'PRIMARY'

**Comment by prashants** [comment]
I am using foreign key ref. in this version to ensure data integrity. For inserting a ledger account, it has a field called parent_id that references a id in the group table. If the id in the group table is not present it will not insert the data. This is done through foreign key ref.

You can either add data in the order of groups, ledgers, entrytypes, tags, entries, entryitems, settings, logs. This will maintain the ref. checks.

OR

What you can do is delete all foreign key code in the update script. The lines after /\* ADD FOREIGN KEY CONSTRAINT _/ to lines before /_ ADD TRIGGERS */

Then try inserting the data.

**Comment by prashants** [comment]
As per the error, you already have a row with id = 3 in the entries table. Check the database for any existing data.

**Comment by hidayat-ullah** [comment]
ok

**Comment by hidayat-ullah** [comment]
there is no duplicate entry in database 
but its still showing error
#1062 - Duplicate entry '5' for key 'PRIMARY'

**Comment by prashants** [comment]
If possible email me the database dump or meet me on team viewer tom.

**Comment by prashants** [comment]
One more option is to import the data first then run the update script.

**Comment by hidayat-ullah** [comment]
ok.., let me send DB check your mail

**Comment by prashants** [comment]
Got the email. I will check and let you know.

**Comment by hidayat-ullah** [comment]
ok

**Comment by hidayat-ullah** [comment]
have you checked..?

**Comment by prashants** [comment]
Sorry I was busy with the release. There are some bugs that came up after the release so didn't check it. I will do it by tom.

**Comment by prashants** [comment]
I was able to migration by just running the migration script against the data file you gave me. Check your email for more details.

**Comment by prashants** [comment]
I am closing this issue for now since this repository is no longer active. Please open a new issues below

https://github.com/prashants/webzash/issues
